apiVersion: v2
name: act-runner-scale-set
description: A configurable act_runner scale set for Gitea Actions on Kubernetes
type: application
version: 0.2.16
appVersion: "0.2.16"
home: https://github.com/00o-sh/act_runner
sources:
  - https://github.com/00o-sh/act_runner
  - https://gitea.com/gitea/act_runner
keywords:
  - gitea
  - actions
  - runner
  - ci
  - cd
  - scale-set
icon: https://gitea.com/assets/img/logo.svg
