apiVersion: v2
name: act-runner-scale-set
description: A configurable act_runner scale set for Gitea Actions on Kubernetes
type: application
version: 0.1.0
appVersion: "0.2.11"
home: https://gitea.com/gitea/act_runner
sources:
  - https://gitea.com/gitea/act_runner
keywords:
  - gitea
  - actions
  - runner
  - ci
  - cd
  - scale-set
maintainers:
  - name: act-runner-scale-set
