{{- if and .Values.keda.enabled (not .Values.ephemeral) }}
{{- $fullname := include "act-runner-scale-set.fullname" . -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "act-runner-scale-set.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    {{- if .Values.persistence.enabled }}
    kind: StatefulSet
    {{- else }}
    kind: Deployment
    {{- end }}
    name: {{ $fullname }}
  minReplicaCount: {{ .Values.minRunners | default 1 }}
  maxReplicaCount: {{ .Values.maxRunners | default 10 }}
  pollingInterval: {{ .Values.keda.pollingInterval | default 30 }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default 300 }}
  triggers:
    - type: metrics-api
      metadata:
        {{- $url := .Values.keda.forgejoApiUrl | default "" | trimSuffix "/" }}
        {{- if eq (.Values.keda.forgejoApiScope | default "admin") "org" }}
        url: "{{ $url }}/api/v1/orgs/{{ .Values.keda.forgejoOrg | default "" }}/actions/jobs?status=waiting&limit=1"
        {{- else }}
        url: "{{ $url }}/api/v1/admin/actions/jobs?status=waiting&limit=1"
        {{- end }}
        valueLocation: "total_count"
        targetValue: "1"
        authMode: "bearer"
        {{- if .Values.keda.unsafeSsl }}
        unsafeSsl: "true"
        {{- end }}
      authenticationRef:
        name: {{ .Values.keda.triggerAuthenticationRef | default "" }}
{{- end }}
