{{- if include "act-runner-scale-set.useScaledJob" . }}
{{- $fullname := include "act-runner-scale-set.fullname" . -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "act-runner-scale-set.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobTargetRef:
    backoffLimit: 0
    ttlSecondsAfterFinished: {{ .Values.keda.scaledJob.ttlSecondsAfterFinished | default 300 }}
    template:
      {{- include "act-runner-scale-set.runnerPodTemplate" . | nindent 6 }}
  pollingInterval: {{ .Values.keda.pollingInterval | default 30 }}
  maxReplicaCount: {{ .Values.maxRunners | default 10 }}
  minReplicaCount: {{ .Values.minRunners | default 0 }}
  successfulJobsHistoryLimit: {{ .Values.keda.scaledJob.successfulJobsHistoryLimit | default 5 }}
  failedJobsHistoryLimit: {{ .Values.keda.scaledJob.failedJobsHistoryLimit | default 5 }}
  {{- if .Values.keda.scaledJob.scalingStrategy }}
  scalingStrategy:
    strategy: {{ .Values.keda.scaledJob.scalingStrategy | default "default" | quote }}
  {{- end }}
  triggers:
    - type: metrics-api
      metadata:
        {{- $url := .Values.keda.forgejoApiUrl | default "" | trimSuffix "/" }}
        {{- if eq (.Values.keda.forgejoApiScope | default "admin") "org" }}
        url: "{{ $url }}/api/v1/orgs/{{ .Values.keda.forgejoOrg | default "" }}/actions/jobs?status=waiting&limit=1"
        {{- else }}
        url: "{{ $url }}/api/v1/admin/actions/jobs?status=waiting&limit=1"
        {{- end }}
        valueLocation: "total_count"
        targetValue: "1"
        authMode: "bearer"
        {{- if .Values.keda.unsafeSsl }}
        unsafeSsl: "true"
        {{- end }}
      authenticationRef:
        name: {{ .Values.keda.triggerAuthenticationRef | default "" }}
{{- end }}
