{{- if include "act-runner-scale-set.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "act-runner-scale-set.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "act-runner-scale-set.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ index .Values.giteaConfigSecret "token" | b64enc | quote }}
{{- end }}
