{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.watchAllNamespaces }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ include "act-runner-controller.fullname" . }}
  labels:
    {{- include "act-runner-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.watchAllNamespaces }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "act-runner-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "act-runner-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
