{{- if include "act-runner-controller.createApiTokenSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "act-runner-controller.apiTokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "act-runner-controller.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.forgejo.apiTokenSecret.key | default "token" }}: {{ .Values.forgejo.apiToken | b64enc | quote }}
{{- end }}
